### ISSUE TITLE
Pas op met console.log()

### ISSUE THREAD

**Issue by KrijnHoetmer** [SemBakkum/Browser-technologies#2]
Er staat nog een `console.log()` in je code. Wat gebeurt er met zo'n regel in een browser die geen `console` ondersteunt?

**Comment by SemBakkum** [comment]
Als je browser console log niet kent, bijv. ie8 dan kan de code breken, maar ik heb ze eruit gehaald hoor :)

**Comment by KoopReynders** [comment]
done
