### ISSUE TITLE
Wat als een browser `classList` niet ondersteunt?

### ISSUE THREAD

**Issue by KrijnHoetmer** [SemBakkum/Browser-technologies#3]
Of `querySelectorAll`, of `addEventListener`. Zoek een browser die een bepaald onderdeel niet ondersteunt, en kijk wat er gebeurt als je je demo er in test. Hoe kun je hier in je code rekening mee houden?

**Comment by SemBakkum** [comment]
Heb een check toegevoegd die controleert of deze functionaliteiten/API's ondersteund worden 'ALA' Cutting the mustard.

**Comment by KoopReynders** [comment]
done
