### ISSUE TITLE
Waar in je JS test je of de browser audio wel ondersteunt?

### ISSUE THREAD

**Issue by KrijnHoetmer** [SemBakkum/Browser-technologies#4]
Je doet nu de aanname: als m'n JavaScript het doet, doet `<audio>` het ook. Maar klopt die aanname wel? Hoe kun je dit robuuster maken?

**Comment by SemBakkum** [comment]
In de if statement check ik nu ook of audio ondersteund wordt door te kijken of een functie van de audio tag aanwezig is.

**Comment by KoopReynders** [comment]
done
