### ISSUE TITLE
Laatste twee geluiden doen gekke dingen

### ISSUE THREAD

**Issue by KrijnHoetmer** [SemBakkum/Browser-technologies#5]
Ik kan je laatste twee sounds niet bedienen met m'n toetsenbord ;(

En in IE8 doet je 'yeah' sound iets anders dan in andere browsers (lees: pas op met attributen op meerdere plekken invullen en ze niet in sync houden, omdat je een deel niet ziet/test; hidden (meta)data is gevaarlijk!).

**Comment by SemBakkum** [comment]
Dat kwam omdat er nog geen geluiden aan verbonden zaten en bij de yeah zat een geluid dat al gebruikt werd, vandaar dat deze raar deed. Nu zitten de geluiden eraan die er aan horen so..... problem solved!

**Comment by KoopReynders** [comment]
done
