### ISSUE TITLE
Opdracht, presentatie & readme

### ISSUE THREAD

**Issue by KoopReynders** [SemBakkum/Browser-technologies#6]
Voor een echte beatbox is het downloaden van losse bestanden niet de core functionaliteit. Als je hier iets op kan vinden en dan enhancements kan toepassen tot een dikke vette flexe lekker interface. Dan kun je hoger scoren ...

**Comment by SemBakkum** [comment]
Ik heb gekeken naar een betere oplossing dan het downloaden van de geluiden, maar dat betekent dat ik met flash aan de gang moet gaan... Na wat overleg met Krijn gaf hij ook aan dat ik dat niet moet willen, vandaar dat het downloaden op dit moment het beste is. Ik heb nu wel de web audio api toegepast om er een betere beatbox van te maken.

**Comment by KoopReynders** [comment]
done
